image: node:18

variables:
  BROWSERSTACK_USERNAME: $BROWSERSTACK_USERNAME
  BROWSERSTACK_ACCESS_KEY: $BROWSERSTACK_ACCESS_KEY

cache:
  paths:
    - node_modules/

stages:
  - test
  - report
  - deploy

before_script:
  - echo "Instalando as dependências!"
  - npm install
  - export $(grep -v '^#' .env | xargs) || true

run_tests:
  stage: test
  script:
    - echo "Executando testes..."
    - npm run test
  artifacts:
    paths:
      - allure-results/ 
      - logs/test-log.txt
    expire_in: 7 days

generate_report:
  stage: report
  script:
    - echo "Gerando relatório de testes!"
    - npm run test:allure
    - mkdir -p public
    - mv allure-report/* public/
  artifacts:
    paths:
      - public/
    expire_in: 7 days

deploy_allure:
  stage: deploy
  script:
    - echo "Publicando Allure Report!"
  artifacts:
    paths:
      - public/
  only:
    - main

pages:
  stage: deploy
  script:
    - mv public/ public_allure
    - mv public_allure public
  artifacts:
    paths:
      - public
  only:
    - main