name: Carrefour Banco [CI Pipeline - Single Job]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    name: Run Tests and Deploy Allure Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Load .env file (if exists)
        run: |
          if [ -f .env ]; then
            cat .env >> $GITHUB_ENV
          fi

      - name: Run Tests
        run: npm run test

      - name: Generate Allure Report
        run: |
          mkdir -p public
          if [ -d allure-results ] && [ "$(ls -A allure-results)" ]; then
            npm run test:allure
          else
            echo "No allure results to report."
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
