name: Carrefour Banco [CI Pipeline for Android and iOS]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Load .env file
        run: |
          if [ -f .env ]; then
            export $(grep -v '^#' .env | xargs)
          fi

      - name: Run Tests
        run: npm run test

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            allure-results/
            logs/test-log.txt

  report:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: ./artifacts

      - name: Generate Allure Report
        run: |
          mkdir -p public
          npm run test:allure
          mv allure-report/* public/

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: public

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: report
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Allure Report
        uses: actions/download-artifact@v2
        with:
          name: allure-report
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
